name: flutter_moda_app
description: Arayüzü yapmaya çalışalım


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  assets:
     - assets/modelgrid1.jpeg
     - assets/modelgrid2.jpeg
     - assets/modelgrid3.jpeg
     - assets/model1.jpeg
     - assets/model2.jpeg
     - assets/model3.jpeg
     - assets/chanellogo.jpg
     - assets/chloelogo.png
     - assets/louisvuitton.jpg
     - assets/dress.jpg
  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Regular.ttf
